baseurl = "http://m0t0k1ch1st0ry.com/"
title = "m0t0k1ch1st0ry"
theme = "ghostwriter"
languageCode = "ja-jp"
googleAnalytics = "UA-40447108-1"
disqusShortname = "m0t0k1ch1st0ry"

[Author]
    name = "m0t0k1ch1"
    profile = "https://github.com/m0t0k1ch1"

[Params]
    intro = true
    headline = "m0t0k1ch1st0ry"
    description = "since 2013"
    github = "https://github.com/m0t0k1ch1"
    #linkedin = "https://linkedin.com/in/XXX"
    #gplus = "https://google.com/XXX"
    twitter = "https://twitter.com/m0t0k1ch1"
    #stackoverflow = "http://stackoverflow.com/users/XXX/YYY"
    fbAppId = "171566516539742"
