baseurl = "https://m0t0k1ch1st0ry.com/"
title = "m0t0k1ch1st0ry"
theme = "ghostwriter"
languageCode = "ja-jp"
googleAnalytics = "UA-40447108-1"
disqusShortname = "m0t0k1ch1st0ry"

[Author]
    name = "m0t0k1ch1"
    profile = "https://github.com/m0t0k1ch1"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "m0t0k1ch1st0ry"
    description = "since 2013"
    github = "https://github.com/m0t0k1ch1"
    twitter = "https://twitter.com/m0t0k1ch1"
    fbAppId = "171566516539742"
    highlightJsLocalUrl = "js/highlight.pack.js"
