baseURL            = "https://m0t0k1ch1st0ry.com/"
title              = "m0t0k1ch1st0ry"
copyright          = "© 2013 m0t0k1ch1"
theme              = "h1st0ry"
googleAnalytics    = "UA-40447108-1"
disqusShortname    = "m0t0k1ch1st0ry"
pygmentsCodeFences = true
pygmentsStyle      = "monokai"

[taxonomies]
    tag = "tags"

[blackfriday]
    hrefTargetBlank = true
