baseURL            = 'https://m0t0k1ch1st0ry.com/'
title              = '#m0t0k1ch1st0ry'
copyright          = '© 2013 <a href="https://linktr.ee/m0t0k1ch1" class="has-text-grey has-text-weight-bold">m0t0k1ch1</a>'
theme              = 'h1st0ry'
paginate           = 10
googleAnalytics    = 'UA-40447108-1'
disqusShortname    = 'm0t0k1ch1st0ry'

[taxonomies]
    tag = 'tags'

[params]
    description  = 'Since 2013'
    mainPageType = 'blog'
    images       = ['img/common/author_256.jpg']
    addthisID    = 'ra-5ce6ac411a98e6f0'

[markup]
    [markup.highlight]
        style = 'rrt'
